### ISSUE TITLE
the code generated for the video

### ISSUE THREAD

**Issue by ZTzxj** [UniModal4Reasoning/AdaptiveDiffusion#1]
Hello, may I ask what part of your method is the code generated for the video shown in the paper, sorry I didn't find it

**Comment by JiakangYuan** [comment]
Hello, and thank you for your interest in our work. The improved video generation models introduced in our paper are available at [L2732](https://github.com/UniModal4Reasoning/AdaptiveDiffusion/blob/0bd1f416d1ac42cea5fdc7226be48dc98d67861f/examples/AdaptiveDiffusion/acceleration/sparse_pipeline.py#L2732) and [L3494](https://github.com/UniModal4Reasoning/AdaptiveDiffusion/blob/0bd1f416d1ac42cea5fdc7226be48dc98d67861f/examples/AdaptiveDiffusion/acceleration/sparse_pipeline.py#L3494). Additionally, we have uploaded a video generation script for evaluation purposes. Please refer to [generate_video.py](https://github.com/UniModal4Reasoning/AdaptiveDiffusion/blob/master/examples/AdaptiveDiffusion/generate_video.py) for more details.

**Comment by ZTzxj** [comment]
Thank you very much for your reply! I would also like to ask if you have any specific requirements for the versions of the packages when configuring the environment?





甄婷
***@***.***

签名由 网易灵犀办公 定制





Original:
From: Jiakang ***@***.***> Date: 2024-10-22 16:34:36 To: ***@***.***> Cc: ***@***.***>, State ***@***.***> Subject: Re: [UniModal4Reasoning/AdaptiveDiffusion] the code generated for the video (Issue #1)
Hello, and thank you for your interest in our work. The improved video generation models introduced in our paper are available at L2732 and L3494. Additionally, we have uploaded a video generation script for evaluation purposes. Please refer to generate_video.py for more details.

**Comment by HankYe** [comment]
Hi, we have demonstrated the effectiveness of our method on the up-to-date version of diffusers. Therefore, as long as you implement the adaptive pipeline based on the same version as the official diffuser's version, it will work.
